name: action

on:
  push:
    branches:
      - deploy

jobs:
  sync-to-gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "신창엽"
          git config --global user.email "schy2504@naver.com"

      - name: Install rsync
        run: sudo apt-get install rsync

      - name: Sync to Gitlab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git clone https://oauth2:$GITLAB_TOKEN@lab.ssafy.com/s10-bigdata-recom-sub2/S10P22D204.git
          cd S10P22D204
          git checkout -b stream
          rsync -av --exclude='.git/' --exclude='.github' ../ stream/
          git add .
          git commit -m "stream server develop update"
          git fetch origin stream
          git merge origin/stream --no-ff --allow-unrelated-histories -m "Merge remote changes"
          git push -u origin stream
